# bundle_id = "domain.id"
# path is the relative path to the workflow in the project root
---
path: workflow
domain: mobiletest.engineer
id: godaddy-domains
# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Library/Mobile Documents/com~apple~CloudDocs/alfred